{
 "title": "Prometheus Blackbox Exporter Ping",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "ICMP RTT",
   "type": "heatmap",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ICMP Packet Loss",
   "type": "heatmap",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "1-avg_over_time(probe_success[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ICMP RTT (WAN)",
   "type": "timeseries",
   "gridPos": { "h": 29, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{phase=\"rtt\", instance!~\"192.168.(.*?)\"} > 0",
     "legendFormat": "{{instance}}"
    },
    { "expr": "0.1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ICMP RTT (LAN)",
   "type": "timeseries",
   "gridPos": { "h": 29, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{phase=\"rtt\", instance=~\"192.168.(.*?)\"} > 0",
     "legendFormat": "{{instance}}"
    },
    { "expr": "0.03", "legendFormat": "__auto" }
   ]
  }
 ]
}