apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus
    url: http://prometheus:9090
    password:
    user:
    database:
    basicAuth:
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    isDefault: true
    version: 1
    editable: false
  - name: InfluxDB_PVE
    type: influxdb
    access: proxy
    uid: influxdb_pve
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: monitoring
      defaultBucket: monitoring
      tlsSkipVerify: true
    secureJsonData:
      token: 123456789
